alias ls='ls --color=auto'
alias reboot='sudo systemctl reboot'
alias poweroff='myRemoteDelBackup.sh && sudo systemctl poweroff'
alias poweroff='myRemoteDelBackup.sh && sudo systemctl poweroff'
alias mount='sudo mount'
alias umount='sudo umount'
alias pacman='sudo pacman'
alias ..='cd ..'
alias swayconf='vim ~/.config/sway/config'
alias waybarconf='vim ~/.config/waybar/config'
alias n='nvim'
alias vim='nvim'
alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias rmr='rm -rf'
alias rotEx='myRotateDisplay.sh'
alias za='zathura --fork'
alias newgradle='shopt -s dotglob && cp -r /home/simon/Documents/Templates/GradleTemplate/* . && shopt -u dotglob'
alias newluds='cp /home/simon/Documents/Templates/LUDS-ex ./ex.tex'
alias newcmake='cp -r /home/simon/Documents/Templates/CMake/* .'
alias newmake='cp -r /home/simon/Documents/Templates/makeTemplate/* .'
alias qbc='myQbtCtrl.py'
complete -F _myQbtCtrl qbc
alias c='clear'
alias sv='source ~/.bashrc'
alias gw='./gradlew'
alias gwb='./gradlew build'
alias pud='pushd'
alias pod='popd'
alias scancp='mount -t vfat -o umask=000 /dev/sdc1 /mnt/ex0/ && cp /mnt/ex0/HPSCANS/scan*.pdf . && chmod 622 scan* && rm /mnt/ex0/HPSCANS/scan*.pdf && umount /dev/sdc1'
alias curl='curl -w "\n"'
alias gs='git status'
alias gti='git'
complete -o bashdefault -o default -o nospace -F __git_wrap__git_main gti
alias g='git'
complete -o bashdefault -o default -o nospace -F __git_wrap__git_main g
alias emu='emulator @emu18 -gpu off -skin 900x1600 &'
alias emustop='killall qemu-system-x86_64'
alias cf='/home/simon/Scripts/myStartConf.sh'
alias scsh='grim -g "$(slurp)" screen.png'
alias pe='perl -lpe'
alias sued='/home/simon/Scripts/mySudoEdit.sh'
alias rs='rsync -ah --progress'
alias less='less -r'
alias p-r='perl-rename'
alias grep='grep --color=auto'
alias cat='bat -p'
alias p='paru'
source /usr/share/bash-completion/completions/paru.bash
complete -F _paru p
alias make='make -j 12'
alias myRemoteDelBackup.sh='myRemoteBackup.sh --delete'
alias myRemoteDelSync.sh='myRemoteSync.sh --delete'
alias lock='cmatrix -abLu 3'
alias :e='nvim'
alias ip='ip -c'
alias zoom='env QT_QPA_PLATFORM=xcb zoom'
alias winsel='swaymsg -t get_tree | jq -r '\''.. | (.nodes? // empty)[] | select(.pid and .visible) | .rect | "\(.x),\(.y) \(.width)x\(.height)"'\'' | slurp'
alias lstyc='stylua -c $(find . -name "*.lua")'
alias set_lsn_src='sed -r "s|[^\n]*luasnip-dev-plug[^\n]*|\tPlug '\''$(pwd)'\'' \"luasnip-dev-plug|g" -i /home/simon/.config/nvim/init.vim'
alias kodi='kodi --windowing=wayland'
alias sus='systemctl suspend'
