alias poweroff='myRemoteDelBackup.sh && sudo systemctl poweroff'
alias poweroff='myRemoteDelBackup.sh && sudo systemctl poweroff'
alias za='zathura --fork'
alias sued='mySudoEdit.sh'
alias myRemoteDelBackup.sh='myRemoteBackup.sh --delete'
alias myRemoteDelSync.sh='myRemoteSync.sh --delete'
alias mc='multimc --launch Fabulously-Optimized-4.6.0-beta.4'
